/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-30 05:30:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.electronicSign;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class absentDocPDF_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write(" <!-- jQuery -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".tg {\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\tborder-spacing: 0;\r\n");
      out.write("\tborder-color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tg td {\r\n");
      out.write("\tfont-family: Arial, sans-serif;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tpadding: 10px 5px;\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tword-break: normal;\r\n");
      out.write("\tborder-color: #ccc;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tg th {\r\n");
      out.write("\tfont-family: Arial, sans-serif;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tpadding: 10px 5px;\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tword-break: normal;\r\n");
      out.write("\tborder-color: #ccc;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tbackground-color: #f0f0f0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tg .tg-cly1 {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tvertical-align: middle\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tg .tg-buh4 {\r\n");
      out.write("\tbackground-color: #f9f9f9;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tvertical-align: top\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tg .tg-yjjc {\r\n");
      out.write("\tbackground-color: #f9f9f9;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tvertical-align: middle\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tg .tg-0lax {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tvertical-align: top\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 767px) {\r\n");
      out.write("\t.tg {\r\n");
      out.write("\t\twidth: auto !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tg col {\r\n");
      out.write("\t\twidth: auto !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tg-wrap {\r\n");
      out.write("\t\toverflow-x: auto;\r\n");
      out.write("\t\t-webkit-overflow-scrolling: touch;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrapper {\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\theight: 800px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#first-first {\r\n");
      out.write("\twidth: 25%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#first-second {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#first-third {\r\n");
      out.write("\twidth: 25%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tg {\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\tborder-spacing: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tg td {\r\n");
      out.write("\tfont-family: Arial, sans-serif;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tpadding: 10px 5px;\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tword-break: normal;\r\n");
      out.write("\tborder-color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tg th {\r\n");
      out.write("\tfont-family: Arial, sans-serif;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tpadding: 10px 5px;\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tword-break: normal;\r\n");
      out.write("\tborder-color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tg .tg-0pky {\r\n");
      out.write("\tborder-color: black;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tvertical-align: middle\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tg .tg-0lax {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tvertical-align: middle\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <h2 style=\"text-align: center;\">결근사유서</h2>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<!-- 첫 번째 div -->\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t<div id=\"first-first\" class=\"tg-wrap\">\r\n");
      out.write("\t\t\t\t<table class=\"tg\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"tg-cly1\">문서번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 150px;\">99</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"tg-cly1\">작성일자</th>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 150px;\">2020/02/29</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"tg-cly1\">신청부서</th>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 150px;\">인사팀</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"tg-0lax\">신청자</th>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 150px;\">한송희</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"first-second\"></div>\r\n");
      out.write("\t\t\t<div id=\"first-third\" class=\"tg-wrap\">\r\n");
      out.write("\t\t\t\t<table class=\"tg\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"tg-yla0\" rowspan=\"3\">결재</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"tg-nrix\">부장</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"tg-baqh\">상무</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"tg-baqh\">사장</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tg-nrix\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tg-baqh\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tg-baqh\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tg-nrix\">2020/02/28</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tg-baqh\">2020/02/29</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tg-baqh\">2020/03/02</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<!-- 두 번째 div -->\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<table class=\"tg\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"tg-0pky\">제목</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"tg-0pky\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"tg-0pky\">기간</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"tg-0pky\">2020 년 02 월 28일 부터 ~ 2020 년 02 월 28일 까지\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;(1 일간)</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"tg-0pky\">결근사유</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"tg-0pky\" colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"tg-0pky\">비고</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"tg-0pky\" colspan=\"2\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"tg-0lax\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<p>위와 같은 내용으로 결근사유서를 제출합니다.</p>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"text-align: center;\">2020년 02 월 29 일</p>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"text-align: right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<sub>신청인: 한송희(인)</sub>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"tg-0lax\" colspan=\"2\" style=\"text-align: left;\"><br>①\r\n");
      out.write("\t\t\t\t\t\t천재지변 등 부득이하게 결근한 경우에는 결근 익일 퇴근시 까지 결근사유서를 제출하기 바랍니다.<br>②&nbsp;&nbsp;결근일수가\r\n");
      out.write("\t\t\t\t\t\t1주일 이상이 될 경우에는 의사의 진단서나 기타 증명서를 첨부해야 합니다.<br></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<hr>\r\n");
      out.write("<br>\r\n");
      out.write("     <!--  <button onclick=\"printPdf()\" style=\"width: 100px; height: 50px; float: right; border: 1px solid lightgrey\">인쇄</button> -->\r\n");
      out.write("        \r\n");
      out.write("</div>\r\n");
      out.write("\t<script type=\"text/javascript\"> \r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\twindow.print();\r\n");
      out.write("\t});\r\n");
      out.write("\t/* function printPdf(){\r\n");
      out.write("\t\twindow.print();\r\n");
      out.write("\t} */\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
