/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-29 11:24:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.electronicSign;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class holidayRequestDraft_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>(주) 오정상사 그룹웨어 - 전자결재</title>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script\r\n");
      out.write("   src=\"");
      out.print(request.getContextPath());
      out.write("/resources/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("<!-- Ionicons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("<!-- Theme style -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/dist/css/adminlte.min.css\">\r\n");
      out.write("<!-- Google Font: Source Sans Pro -->\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition sidebar-mini\">\r\n");
      out.write("\r\n");
      out.write("   <div class=\"wrapper\">\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/nav.jsp", out, false);
      out.write("\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Content Wrapper. Contains page content -->\r\n");
      out.write("      <div class=\"content-wrapper\">\r\n");
      out.write("         <!-- Content Header (Page header) -->\r\n");
      out.write("         <section class=\"content-header\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("               <div class=\"row mb-2\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.container-fluid -->\r\n");
      out.write("         </section>\r\n");
      out.write("         <!-- Main content -->\r\n");
      out.write("         <form class=\"form-horizontal\" method=\"POST\" action=\"insertHolidayRequest\"\r\n");
      out.write("         onsubmit=\"return validate();\"\r\n");
      out.write("            enctype=\"multipart/form-data\" role=\"form\">\r\n");
      out.write("            <section class=\"content\">\r\n");
      out.write("               <div class=\"container-fluid\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <!-- left column -->\r\n");
      out.write("                     <div class=\"col-md-10\">\r\n");
      out.write("                        <!-- Horizontal Form -->\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                           <div class=\"card-header bg-navy\">\r\n");
      out.write("                              <h3 class=\"card-title\">휴가신청서 작성</h3>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"width: 95%;\">\r\n");
      out.write("\r\n");
      out.write("                           <!-- /.card-header -->\r\n");
      out.write("                           <!-- form start -->\r\n");
      out.write("                           <div class=\"card-body\">\r\n");
      out.write("                              <div class=\"form-group row\">\r\n");
      out.write("                                 <label for=\"inputPassword3\" class=\"col-sm-2 col-form-label\"\r\n");
      out.write("                                    style=\"text-align: center;\">제목</label>\r\n");
      out.write("                                 <div class=\"col-sm-10\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"docTitle\"\r\n");
      out.write("                                       id=\"docTitle\" placeholder=\"제목을 입력해주세요.\">\r\n");
      out.write("                                 </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <!--                               <div class=\"form-group row\">\r\n");
      out.write("                                 <label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\"\r\n");
      out.write("                                    style=\"text-align: center;\">일자</label>\r\n");
      out.write("                                 <div class=\"col-sm-10\">\r\n");
      out.write("                                    <input type=\"date\" class=\"form-control\" id=\"inputEmail3\">\r\n");
      out.write("                                 </div>\r\n");
      out.write("                              </div>\r\n");
      out.write(" -->\r\n");
      out.write("                              <div class=\"form-group row\">\r\n");
      out.write("                                 <label for=\"inputTitle3\" class=\"col-sm-2  col-form-label\"\r\n");
      out.write("                                    style=\"text-align: center;\" style=\"margin-bottom: 0;\">첨부파일</label>\r\n");
      out.write("                                 <div class=\"col-sm-10\">\r\n");
      out.write("                                    <div class=\"custom-file\">\r\n");
      out.write("                                       <label class=\"custom-file-label\" for=\"exampleInputFile\">\r\n");
      out.write("                                       </label> <input type=\"file\" class=\"custom-file-input\"\r\n");
      out.write("                                          multiple=\"multiple\" id=\"exampleInputFile\" name=\"docFile\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("\r\n");
      out.write("                              <div class=\"form-group row\">\r\n");
      out.write("                                 <label for=\"inputPassword3\" class=\"col-sm-2 col-form-label\"\r\n");
      out.write("                                    style=\"text-align: center;\">결재라인 선택</label>\r\n");
      out.write("                                 <!-- 결재 라인 버튼 넣기 -->\r\n");
      out.write("\r\n");
      out.write("                                 <div class=\"card-footer text-right\">\r\n");
      out.write("                                    <!-- 결재라인 모달 시작-->\r\n");
      out.write("                                    <a id=\"modal-12110922\" role=\"button\"\r\n");
      out.write("                                       class=\"btn btn btn-outline-secondary\"\r\n");
      out.write("                                       data-target=\"#modal-container-12110922\" data-toggle=\"modal\">결재라인</a>\r\n");
      out.write("                                    <!-- href=\"#modal-container-12110922\" -->\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"modal fade \" id=\"modal-container-12110922\">\r\n");
      out.write("                                       <!--    role=\"dialog\" aria-labelledby=\"myModalLabel\"\r\n");
      out.write("                                       aria-hidden=\"true\" -->\r\n");
      out.write("                                       <div class=\"modal-dialog modal-lg\"\r\n");
      out.write("                                          style=\"width: 1000px; margin-left: 250px; margin-top: 100px; display: table;\"\r\n");
      out.write("                                          role=\"document\">\r\n");
      out.write("                                          <div class=\"modal-content\">\r\n");
      out.write("                                             <!--              id=\"modal-12110922\" -->\r\n");
      out.write("\r\n");
      out.write("                                             <div class=\"card\">\r\n");
      out.write("                                                <div class=\"card-header bg-navy\">\r\n");
      out.write("                                                   <h3 class=\"card-title\">결재라인</h3>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"card-body\">\r\n");
      out.write("                                                   <div class=\"row\">\r\n");
      out.write("                                                      <div class=\"col-md-3 ml-3\" style=\"text-align: left;\">\r\n");
      out.write("                                                         <table class=\"table\" id=\"selectDepartment\"\r\n");
      out.write("                                                            style=\"width: 100%; border: 1px solid rgba(176, 196, 222, 0.726)\">\r\n");
      out.write("                                                            <thead\r\n");
      out.write("                                                               style=\"font-size: large; font-weight: bold; background-color: rgba(176, 196, 222, 0.726);\">\r\n");
      out.write("                                                               <th>부서 선택</th>\r\n");
      out.write("                                                            </thead>\r\n");
      out.write("                                                            <tbody>\r\n");
      out.write("                                                               <tr>\r\n");
      out.write("                                                                  <td><input type=\"radio\" id=\"D1\" value=\"D1\"\r\n");
      out.write("                                                                     name=\"group1\" class=\"selectDepartment1\">\r\n");
      out.write("                                                                     <label for=\"D1\">개발부서</label></td>\r\n");
      out.write("                                                               </tr>\r\n");
      out.write("                                                               <tr>\r\n");
      out.write("                                                                  <td><input type=\"radio\" id=\"D2\" value=\"D2\"\r\n");
      out.write("                                                                     name=\"group1\" class=\"selectDepartment1\">\r\n");
      out.write("                                                                     <label for=\"D2\">경영지원부서</label></td>\r\n");
      out.write("                                                               </tr>\r\n");
      out.write("                                                               <tr>\r\n");
      out.write("                                                                  <td><input type=\"radio\" id=\"D3\" value=\"D3\"\r\n");
      out.write("                                                                     name=\"group1\" class=\"selectDepartment1\">\r\n");
      out.write("                                                                     <label for=\"D3\">회계부서</label></td>\r\n");
      out.write("                                                               </tr>\r\n");
      out.write("                                                               <tr>\r\n");
      out.write("                                                                  <td><input type=\"radio\" id=\"D4\" value=\"D4\"\r\n");
      out.write("                                                                     name=\"group1\" class=\"selectDepartment1\">\r\n");
      out.write("                                                                     <label for=\"D4\">인사부서</label></td>\r\n");
      out.write("                                                               </tr>\r\n");
      out.write("                                                               <tr>\r\n");
      out.write("                                                                  <td><input type=\"radio\" id=\"D5\" value=\"D5\"\r\n");
      out.write("                                                                     name=\"group1\" class=\"selectDepartment1\">\r\n");
      out.write("                                                                     <label for=\"D5\">마케팅부서</label></td>\r\n");
      out.write("                                                               </tr>\r\n");
      out.write("                                                               <tr>\r\n");
      out.write("                                                                  <td><input type=\"radio\" id=\"D6\" value=\"D6\"\r\n");
      out.write("                                                                     name=\"group1\" class=\"selectDepartment1\">\r\n");
      out.write("                                                                     <label for=\"D6\">영업부서</label></td>\r\n");
      out.write("                                                               </tr>\r\n");
      out.write("                                                            </tbody>\r\n");
      out.write("                                                         </table>\r\n");
      out.write("                                                      </div>\r\n");
      out.write("\r\n");
      out.write("                                                      <div class=\"col-md-3\" style=\"text-align: left;\">\r\n");
      out.write("                                                         <table class=\"table\" id=\"selectRecieverName\"\r\n");
      out.write("                                                            style=\"height: 100px; overflow-x: scroll; overflow-y: hidden; border: 1px solid rgba(176, 196, 222, 0.726)\">\r\n");
      out.write("                                                            <thead\r\n");
      out.write("                                                               style=\"font-size: large; font-weight: bold; background-color: rgba(176, 196, 222, 0.726);\">\r\n");
      out.write("                                                               <th>결재자 & 결재구분 선택</th>\r\n");
      out.write("                                                            </thead>\r\n");
      out.write("                                                            <tbody id=\"deptListOut\"\r\n");
      out.write("                                                               style=\"height: 100px; overflow-x: scroll; overflow-y: hidden;\">\r\n");
      out.write("\r\n");
      out.write("                                                            </tbody>\r\n");
      out.write("                                                         </table>\r\n");
      out.write("                                                      </div>\r\n");
      out.write("\r\n");
      out.write("                                                      <div class=\"col-md-1\">\r\n");
      out.write("                                                         <br> <br> <br> <br> <br> <br>\r\n");
      out.write("                                                         <br> <i\r\n");
      out.write("                                                            class=\"fas fa-angle-double-right fa-2x mr-3\"></i>\r\n");
      out.write("                                                      </div>\r\n");
      out.write("\r\n");
      out.write("                                                      <div class=\"col-md-4 ml-2\" style=\"text-align: left;\">\r\n");
      out.write("                                                         <table class=\"table\" id=\"checkSignName\"\r\n");
      out.write("                                                            style=\"height: 100px; overflow-x: scroll; overflow-y: hidden; border: 1px solid rgba(176, 196, 222, 0.726)\">\r\n");
      out.write("                                                            <thead\r\n");
      out.write("                                                               style=\"font-size: large; font-weight: bold; background-color: rgba(176, 196, 222, 0.726);\">\r\n");
      out.write("                                                               <th>결재목록 확인</th>\r\n");
      out.write("                                                            </thead>\r\n");
      out.write("                                                            <tbody style=\"height: 100px; overflow-x: scroll; overflow-y: hidden;\">\r\n");
      out.write("                                                            <tr>\r\n");
      out.write("                                                            </tbody>\r\n");
      out.write("                                                         </table>\r\n");
      out.write("                                                      </div>\r\n");
      out.write("\r\n");
      out.write("                                                   </div>\r\n");
      out.write("                                                   <!-- row종료 -->\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <!-- 모달 카드바디 종료 -->\r\n");
      out.write("                                             </div>\r\n");
      out.write("\r\n");
      out.write("                                             <div class=\"modal-footer\" style=\"padding-right: 50px;\">\r\n");
      out.write("                                                <input type=\"button\" class=\"btn btn-outline-primary\"\r\n");
      out.write("                                                   id=\"selectBtn\" value=\"선택\">\r\n");
      out.write("                                                <button type=\"button\" class=\"btn btn-outline-secondary\" id=\"removeSelect\"\r\n");
      out.write("                                                   data-dismiss=\"modal\" aria-label=\"Close\">취소</button>\r\n");
      out.write("                                                <button id=\"makeLine\" type=\"button\" class=\"btn btn-outline-danger\" data-dismiss=\"modal\">결재라인   등록</button>\r\n");
      out.write("                                             </div>\r\n");
      out.write("\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                       </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- 모달 끝 -->\r\n");
      out.write("                                 </div>\r\n");
      out.write("\r\n");
      out.write("                         </div>\r\n");
      out.write("                             <div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"date\" class=\"col-sm-2 col-form-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align: center;\">일자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" id=\"startDate\" name=\"docRemark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mt-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<sub>부터</sub>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" id=\"endDate\" name=\"docRemark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mt-2\"> <sub>까지</sub> </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mt-2\"> <sub>총 </sub> </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"startDate\" style=\"width: 50px;\" maxlength=\"3\" name=\"docRemark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mt-2\"> <sub>일</sub> </p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("                      <label for=\"inputPassword3\" class=\"col-md-2 col-form-label\"\r\n");
      out.write("                        style=\"text-align: center;\">휴가 종류</label>\r\n");
      out.write("                      <div class=\"col-md-4 \">\r\n");
      out.write("                        <select class=\"form-control\" id=\"selectBox\" name=\"docRemark\">\r\n");
      out.write("                            <option value=\"\" selected>휴가 종류를 선택해주세요</option>\r\n");
      out.write("                            <option value=\"연차\">연차</option>\r\n");
      out.write("                            <option value=\"반차\">반차</option>\r\n");
      out.write("                            <option value=\"병가\">병가</option>\r\n");
      out.write("                            <option value=\"기타\">기타</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                              <script>\r\n");
      out.write("                                 // 수신인  경로;\r\n");
      out.write("                                 \r\n");
      out.write("\r\n");
      out.write("                                 $('input[name=group1]')\r\n");
      out.write("                                       .click( function() {\r\n");
      out.write("                                                var radioValue = $(\r\n");
      out.write("                                                      this)\r\n");
      out.write("                                                      .val();\r\n");
      out.write("\r\n");
      out.write("                                                $\r\n");
      out.write("                                                      .ajax({\r\n");
      out.write("                                                         url : \"msgSelectDepartment\",\r\n");
      out.write("                                                         type : \"post\",\r\n");
      out.write("                                                         data : {\r\n");
      out.write("                                                            radioValue : radioValue\r\n");
      out.write("                                                         },\r\n");
      out.write("                                                         dataType : \"json\",\r\n");
      out.write("                                                         success : function(\r\n");
      out.write("                                                               mList) {\r\n");
      out.write("\r\n");
      out.write("                                                            $(\r\n");
      out.write("                                                                  \"#deptListOut\")\r\n");
      out.write("                                                                  .html(\r\n");
      out.write("                                                                        \"\");\r\n");
      out.write("\r\n");
      out.write("                                                            var td = \"\";\r\n");
      out.write("                                                            for ( var i in mList) {\r\n");
      out.write("                                                               td += \"<tr><td>\"\r\n");
      out.write("                                                                     + \"&nbsp\"\r\n");
      out.write("                                                                     + \"<input type='radio' name='group2'  value='\"+mList[i].memberNo + \"'>\"\r\n");
      out.write("                                                                     + \"<input type='hidden' id='memberName' name='memberName' value='\" + mList[i].memberName  + \"'>\"\r\n");
      out.write("                                                                     + \"<input type='hidden' value='\" + mList[i].jobName  + \"'>\"\r\n");
      out.write("                                                                     + \"<lable for = 'selectReciever'>\"\r\n");
      out.write("                                                                     + mList[i].memberName\r\n");
      out.write("                                                                     + \"   /   \"\r\n");
      out.write("                                                                     + mList[i].jobName\r\n");
      out.write("                                                                     + \"</label>\"\r\n");
      out.write("                                                                     + \"&nbsp;&nbsp;\"\r\n");
      out.write("                                                                     + \"<select class='targetSelect'\" + i + \" style='width:70px;'>\"\r\n");
      out.write("                                                                     + \"<option value='1'>\"\r\n");
      out.write("                                                                     + '합의'\r\n");
      out.write("                                                                     + \"</option>\"\r\n");
      out.write("                                                                     + \"<option value='2'>\"\r\n");
      out.write("                                                                     + '결재'\r\n");
      out.write("                                                                     + \"</option>\"\r\n");
      out.write("                                                                     + \"</select>\"\r\n");
      out.write("                                                                     + \"</td></tr>\";\r\n");
      out.write("                                                            }\r\n");
      out.write("\r\n");
      out.write("                                                            $(\r\n");
      out.write("                                                                  \"#deptListOut\")\r\n");
      out.write("                                                                  .html(\r\n");
      out.write("                                                                        td);\r\n");
      out.write("                                                         }\r\n");
      out.write("                                                      });\r\n");
      out.write("                                             });\r\n");
      out.write("                              </script>\r\n");
      out.write("\r\n");
      out.write("                              <script>\r\n");
      out.write("                              var printNm = 0;\r\n");
      out.write("                              var count = 0;\r\n");
      out.write("                              var arr = [];\r\n");
      out.write("                           \t  var checkSign;\r\n");
      out.write("                                 $(\"#selectBtn\").click(function() {\r\n");
      out.write("\r\n");
      out.write("                                                // 결재자 회원번호\r\n");
      out.write("                                                var memberNoVal = $('input[name=\"group2\"]:checked').val();\r\n");
      out.write("                                                console.log(\"memberNoVal : \"+ memberNoVal);\r\n");
      out.write("\r\n");
      out.write("                                                // 결재자 이름\r\n");
      out.write("                                                var nameVal = $('input[name=\"group2\"]:checked').next().val();\r\n");
      out.write("                                                console.log(\"nameVal : \"+ nameVal);\r\n");
      out.write("                                                \r\n");
      out.write("                                                // 결재자 직급\r\n");
      out.write("                                                var jobVal = $('input[name=\"group2\"]:checked').next().next().val();\r\n");
      out.write("                                                console.log(\"jobVal : \"+jobVal);\r\n");
      out.write("   \r\n");
      out.write("                                                \r\n");
      out.write("                                                // 결재 구분  1: 합의   2:결재\r\n");
      out.write("                                                checkSign = $(\r\n");
      out.write("                                                      'input[name=\"group2\"]:checked')\r\n");
      out.write("                                                      .next()\r\n");
      out.write("                                                      .next().next()\r\n");
      out.write("                                                      .children()\r\n");
      out.write("                                                      .children(\r\n");
      out.write("                                                            \"option:selected\")\r\n");
      out.write("                                                      .val();\r\n");
      out.write("                                                console\r\n");
      out.write("                                                      .log(\"checkSign : \"\r\n");
      out.write("                                                            + checkSign);\r\n");
      out.write("\r\n");
      out.write("                                                // 결재 구분 이름 (사용자 확인용)\r\n");
      out.write("                                                var checkSignName = $('input[name=\"group2\"]:checked').next().next().next().children().children(\"option:selected\").text();\r\n");
      out.write("                                                console.log(\"checkSignName : \" + checkSignName);\r\n");
      out.write("                                                var index = $(\"#checkSignName option\").index(\r\n");
      out.write("                                                            $(\"#checkSignName option:selected\"));\r\n");
      out.write("                                                console.log(\"index : \" + index);\r\n");
      out.write("\r\n");
      out.write("                                                var td = \"\";\r\n");
      out.write("\r\n");
      out.write("                                                var $tr = $(\"<tr>\");\r\n");
      out.write("                                                //$('input[name=\"group2\"]:checked').next().next().children().children(\"option:selected\").val();\r\n");
      out.write("                                                $tr.append(\"<td name='lineContent'>\"\r\n");
      out.write("                                                            + \"<span name='group2'>\"\r\n");
      out.write("                                                            + nameVal\r\n");
      out.write("                                                            + \"/\"\r\n");
      out.write("                                                            + jobVal\r\n");
      out.write("                                                            + \"[\"\r\n");
      out.write("                                                            + checkSignName\r\n");
      out.write("                                                            + \"]\"\r\n");
      out.write("                                                            + \"<input type='hidden' name='memberNo' value='\" + memberNoVal + \">\"\r\n");
      out.write("                                                            + \"<input type='hidden' name='checkSign' value='\" + checkSign + \"'>\"\r\n");
      out.write("                                                            + \"</span>\"\r\n");
      out.write("                                                            + \"<i id='test' onclick='removeLine();' class='far fa-minus-square' style='color:red; padding-left:150px;'>삭제</i>\"\r\n");
      out.write("                                                            + \"</td>\");\r\n");
      out.write("                                                $(\"#checkSignName tbody\").append($tr);\r\n");
      out.write("                                                var isEmpty = function(value){ \r\n");
      out.write("                                                   if( value == \"\" || value == null || value == undefined || ( value != null && typeof value == \"object\" && !Object.keys(value).length ) ){ \r\n");
      out.write("                                                      return true \r\n");
      out.write("                                                   }else{ \r\n");
      out.write("                                                      return false }\r\n");
      out.write("                                                };\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                if(isEmpty(arr)){\r\n");
      out.write("                                                arr.push(memberNoVal +\":\"+ nameVal +\":\"+ count +\":\"+jobVal +\":\" + checkSign);}\r\n");
      out.write("                                                else{arr.push(\"||\"+memberNoVal +\":\"+ nameVal +\":\"+ count +\":\"+jobVal +\":\" + checkSign);\r\n");
      out.write("                                                }\r\n");
      out.write("                                                \r\n");
      out.write("                                                printNm = count;\r\n");
      out.write("                                                count +=1;\r\n");
      out.write("                     \r\n");
      out.write("                                             });\r\n");
      out.write("\r\n");
      out.write("                                 function selectNo() {\r\n");
      out.write("                                    return memberNoVal;\r\n");
      out.write("                                 };\r\n");
      out.write("                                 \r\n");
      out.write("                                 // 화면상에는 보이지 않지만, 값이 남아있음.. + 모든 선택사항들이 지워져버림..\r\n");
      out.write("                                 function removeLine(){\r\n");
      out.write("                                    $(\"td[name=lineContent]\").remove();\r\n");
      out.write("                                    $(\"span[name=group2]\").remove();\r\n");
      out.write("                                 };\r\n");
      out.write("                                 $(\"#makeLine\").on(\"click\",function(){\r\n");
      out.write("                                    console.log(arr);\r\n");
      out.write("                                    for(var i in arr){\r\n");
      out.write("                                       \r\n");
      out.write("                                    var afterStr = arr[i].split(\":\");\r\n");
      out.write("                                    console.log(afterStr[1]);\r\n");
      out.write("                                    var checkcheck = afterStr[4];\r\n");
      out.write("                                    var checkcheckName = \"\";\r\n");
      out.write("                                    if(checkcheck == 1){\r\n");
      out.write("                                    \tcheckcheckName=\"합의\";\r\n");
      out.write("                                    }else{\r\n");
      out.write("                                    \tcheckcheckName=\"결재\";\r\n");
      out.write("                                    }\r\n");
      out.write("                                    var $li = $(\"<li>\").prop\r\n");
      out.write("                                    (\"class\",\"list-group-item d-flex justify-content-between align-items-center\")\r\n");
      out.write("                                    .text(afterStr[1]);\r\n");
      out.write("                                    \r\n");
      out.write("                                    var $badge=$(\"<span>\").prop(\"class\", \"badge badge-secondary badge-pill\").text(checkcheckName);\r\n");
      out.write("                                    $li.append($badge); \r\n");
      out.write("                                    \r\n");
      out.write("                                    var $arrow =$(\"<i>\").prop\r\n");
      out.write("                                    (\"class\", \"fas fa-angle-down fa-2x mt-2 mb-2 ml-5\");\r\n");
      out.write("                                 \t\r\n");
      out.write("                                    $(\"#lines\").append($arrow);\r\n");
      out.write("                                    $(\"#lines\").append($li)\r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                    } \r\n");
      out.write("                                    \r\n");
      out.write("                                    $(\"#docSignPath\").val(arr);\r\n");
      out.write("                                 });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                 \r\n");
      out.write("                              </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                              <hr class=\"ml-5\">\r\n");
      out.write("                              <br>\r\n");
      out.write("\r\n");
      out.write("                              <table style=\"width: 100%;\">\r\n");
      out.write("                                 <tr>\r\n");
      out.write("                                    <td colspan=\"3\">&nbsp;&nbsp;</td>\r\n");
      out.write("                                    <td><textarea class=\"textarea\" name=\"docContents\"\r\n");
      out.write("                                          placeholder=\"Place some text here\"\r\n");
      out.write("                                          style=\"width: 99%; height: 500px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px; resize: none;\"></textarea>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                 </tr>\r\n");
      out.write("                              </table>\r\n");
      out.write("                              <br>\r\n");
      out.write("\r\n");
      out.write("                              <div>\r\n");
      out.write("                                 <button type=\"submit\" class=\"btn btn-primary\" onclick=\"test()\"\r\n");
      out.write("                                    style=\"float: right; margin-right: 2%; width: 100px; height: 40px;\">\r\n");
      out.write("                                    <!--  onclick=\"location.href = 'insertNightMeal';\" -->\r\n");
      out.write("                                    결재 등록\r\n");
      out.write("                                 </button>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <!-- /.card-body -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- div style``종료 -->\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <!-- col-md=10 종료-->\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction test(){\r\n");
      out.write("\t\t\t\t   \t//var selectVal = $(\"#selectBox\").val()\r\n");
      out.write("\t\t\t\t   \t//console.log(selectVal);\r\n");
      out.write("\t\t\t\t\tvar remark = document.getElementsByName(\"docRemark\");  \r\n");
      out.write("\t\t\t\t\tvar remarks = new Array();\r\n");
      out.write("\t\t\t\t\tfor( var i=0; i<remark.length ; i++) {\r\n");
      out.write("\t\t\t\t\t\tremarks.push(remark[i].value);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tconsole.log(remarks);\r\n");
      out.write("\t\t\t\t\t\t$(\"#docRemark\").val(remarks);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t </script>\r\n");
      out.write("\r\n");
      out.write("                     <div class=\"col-md-2 pl-3\" id=\"lineDiv\">\r\n");
      out.write("                           <div class=\"card row\" >\r\n");
      out.write("                              <div class=\"card-header bg-navy\">\r\n");
      out.write("                                 <h3 class=\"card-title\">\r\n");
      out.write("                                    <i class=\"fas fa fa-book-reader\"></i>&nbsp; 결재선\r\n");
      out.write("                                 </h3>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <!-- /.card-header -->\r\n");
      out.write("                              <!-- form start -->\r\n");
      out.write("                              <div class=\"card-body\">\r\n");
      out.write("                                 <ul class=\"list-group\" id=\"lines\">\r\n");
      out.write("                                    <li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                      ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                                    <span class=\"badge badge-info badge-pill\">기안</span> \r\n");
      out.write("                                 \t </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" style=\"display:none\" name=\"docSignPath\" id=\"docSignPath\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <!-- cardBody-->\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <!--card row 종료 -->\r\n");
      out.write("                        <!-- row 종료 -->\r\n");
      out.write("\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <!--결재라인 row 끝-->\r\n");
      out.write("                     <!--col-md 2 종료 -->\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </section>\r\n");
      out.write("         </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.container-fluid -->\r\n");
      out.write("      <!-- /.content -->\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- 기안서 작성 화면 끝-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("   <!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("   <!-- REQUIRED SCRIPTS -->\r\n");
      out.write("\r\n");
      out.write("   <!-- bs-custom-file-input -->\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bs-custom-file-input/bs-custom-file-input.min.js\"></script>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("         bsCustomFileInput.init();\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\t\t// 유효성 검사\r\n");
      out.write("\t\tfunction validate() {\r\n");
      out.write("\t\t\tif ($(\"#docTitle\").val().trim().length == 0) {\r\n");
      out.write("\t\t\t\talert(\"제목을 입력해 주세요.\");\r\n");
      out.write("\t\t\t\t$(\"#docTitle\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ($(\"#startDate\").val().trim().length == 0) {\r\n");
      out.write("\t\t\t\talert(\"휴가 시작일을 입력해 주세요.\");\r\n");
      out.write("\t\t\t\t$(\"#startDate\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ($(\"#endDate\").val().trim().length == 0) {\r\n");
      out.write("\t\t\t\talert(\"휴가 종료일을 입력해 주세요.\");\r\n");
      out.write("\t\t\t\t$(\"#endDate\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ($(\"#selectBox\").val()==\"\") {\r\n");
      out.write("\t\t\t\t//alert(\"휴가 종류를 선택해 주세요.\");\r\n");
      out.write("\t\t\t\talert(\"휴가 종류를 선택해 주세요.\" + $(\"#selectBox\").val());\r\n");
      out.write("\t\t\t\t$(\"#selectBox\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ($(\"#docContents\").val().trim().length == 0) {\r\n");
      out.write("\t\t\t\talert(\"내용을 입력해 주세요.\");\r\n");
      out.write("\t\t\t\t$(\"#docContents\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isEmpty(arr)) {\r\n");
      out.write("\t\t\t\talert(\"결재라인을 선택해 주세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\tif($(\"#lines\").hasClass(\"fa-angle-down\")==false){\r\n");
      out.write("\t\t\t\talert(\"결재라인을 선택해 주세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t      // 유효성 검사\r\n");
      out.write("\t      function validate() {\r\n");
      out.write("\t         if(arr.length==0){\r\n");
      out.write("\t            alert(\"결재라인을 선택해주세요.\");\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t         }\r\n");
      out.write("\t         if ($(\"#docTitle\").val().trim().length == 0) {\r\n");
      out.write("\t            alert(\"제목을 입력해 주세요.\");\r\n");
      out.write("\t            $(\"#docTitle\").focus();\r\n");
      out.write("\t            console.log(\"arr.lengh : \" + arr.length);\r\n");
      out.write("\t            console.log(\"docSignPath 1: \" + $(\"#docSignPath\").val());\r\n");
      out.write("\t            console.log(\"docSignPath 2: \" + $(\"#docSignPath\").val().trim().length);\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t         }\r\n");
      out.write("\t         if ($(\"#startDate\").val().trim().length == 0) {\r\n");
      out.write("\t            alert(\"휴가 시작일을 입력해 주세요.\");\r\n");
      out.write("\t            $(\"#startDate\").focus();\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t         }\r\n");
      out.write("\t         if ($(\"#endDate\").val().trim().length == 0) {\r\n");
      out.write("\t            alert(\"휴가 종료일을 입력해 주세요.\");\r\n");
      out.write("\t            $(\"#endDate\").focus();\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t         }\r\n");
      out.write("\t         if ($(\"#selectBox\").val()==\"\") {\r\n");
      out.write("\t            //alert(\"휴가 종류를 선택해 주세요.\");\r\n");
      out.write("\t            alert(\"휴가 종류를 선택해 주세요.\" + $(\"#selectBox\").val());\r\n");
      out.write("\t            $(\"#selectBox\").focus();\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t         }\r\n");
      out.write("\t         if ($(\"#docContents\").val().trim().length == 0) {\r\n");
      out.write("\t            alert(\"내용을 입력해 주세요.\");\r\n");
      out.write("\t            $(\"#docContents\").focus();\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t         }\r\n");
      out.write("\t         else return true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- Bootstrap -->\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("   <!-- AdminLTE -->\r\n");
      out.write("   <!-- OPTIONAL SCRIPTS -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
