/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-15 08:17:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.collaboBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class collaboBoardEditors_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1583419384000L));
    _jspx_dependants.put("jar:file:/C:/workspace/RealFinal/ojungFinal/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspace/RealFinal/ojungFinal/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>(주) 오정상사 그룹웨어 - 전자결재 </title>\n");
      out.write("\n");
      out.write("\t<!-- jQuery -->\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/jquery/jquery.min.js\"></script>\n");
      out.write(" <!-- Tell the browser to be responsive to screen width -->\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <!-- Font Awesome -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/fontawesome-free/css/all.min.css\">\n");
      out.write("  <!-- Ionicons -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\n");
      out.write("  <!-- Theme style -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/dist/css/adminlte.min.css\">\n");
      out.write("  <!-- Google Font: Source Sans Pro -->\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body class=\"hold-transition sidebar-mini\" id=\"dropZone\">\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/nav.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"content-wrapper p-3\">\n");
      out.write("      <!-- Content Header (Page header) -->\n");
      out.write("      <section class=\"content-header\">\n");
      out.write("\n");
      out.write("      <!-- Content Header (Page header) -->\n");
      out.write("  \n");
      out.write("        <div class=\"card\">\n");
      out.write("          <div class=\"card-header bg-navy\">\n");
      out.write("\n");
      out.write("            <h3 class=\"card-title\">협업게시판</h3>\n");
      out.write("              \n");
      out.write("        </div>\n");
      out.write("       \n");
      out.write("  \n");
      out.write("      <!-- Content Wrapper. Contains page content -->\n");
      out.write("\n");
      out.write("      <!-- Main content -->\n");
      out.write("      <form action=\"insert\"  name=\"uploadForm\" id=\"uploadForm\" enctype=\"multipart/form-data\" method=\"POST\">\n");
      out.write("        <section class=\"content\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-md-12\">\n");
      out.write("              <div class=\"card \">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                  <h3 class=\"card-title\">\n");
      out.write("                    <input name=\"collaboTitle\" class=\"form-control \" id=\"inputTitle\" type=\"text\" placeholder=\"제목쓰는 곳\" size=\"150px\">\n");
      out.write("                  </h3>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"card-body pad\">\n");
      out.write("                  <table style=\"width: 85%;\">\n");
      out.write("                      <tr>\n");
      out.write("                        <!-- 협업 대상 체크박스 -->\n");
      out.write("                        <!-- 로그인 멤버의 부서번호 세팅 -->\n");
      out.write("                        ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        <th style=\"text-align: center; font:bold; font-size: 20px;\">대상</th>\n");
      out.write("                        <td>\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                      </tr>\n");
      out.write("\n");
      out.write("                      <!-- 작성자, 작성자 이름은 로그인 한 사람 이름 session에서 받아와서 자동으로 들어가게 하면 좋을거같아요 -->\n");
      out.write("                      <tr>\n");
      out.write("                        <th style=\"text-align: center; font:bold; font-size: 20px;\">작성자</th>\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                      </tr>\n");
      out.write("\n");
      out.write("                      <!-- 업무기한 -->\n");
      out.write("                      <tr>\n");
      out.write("                        <th style=\"text-align: center; font:bold; font-size: 20px;\">업무기한</th>\n");
      out.write("                        <td>\n");
      out.write("                          <div class=\"form-group row\">\n");
      out.write("\t\t                     \t<div class=\"align-items-center justify-content-between\" style=\"text-align: center;\">\n");
      out.write("\t\t\t                      <input type=\"date\" id=\"from\" name=\"collaboStartDate\" class=\"\" style=\"width: 250px;\"> \n");
      out.write("\t\t\t                    </div>&nbsp;&nbsp;-&nbsp;&nbsp;\n");
      out.write("\t\t\t                    <div class=\"\">\n");
      out.write("\t\t\t                      <input type=\"date\" id=\"to\" name=\"collaboEndDate\" class=\"mr-5\" style=\" width: 250px;\"> \n");
      out.write("\t\t\t                    </div>\n");
      out.write("\t\t\t                    <span id=\"betweenDt\"> 일간</span>\n");
      out.write("\t\t                  </div>\n");
      out.write("                              \n");
      out.write("                        </td>\n");
      out.write("                      </tr>\n");
      out.write("                      <!-- 내용 작성 -->\n");
      out.write("                      <tr>\n");
      out.write("                        <th style=\"text-align: center; font:bold; font-size: 20px;\">내용</th>\n");
      out.write("                        <td colspan=\"5\">\n");
      out.write("                          <textarea name=\"collaboContent\" class=\"textarea\" placeholder=\"Place some text here\"\n");
      out.write("                            style=\"width: 100%; height: 300px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px; resize: none;\"></textarea>\n");
      out.write("                        </td>\n");
      out.write("                      </tr>\n");
      out.write("                      <tr>\n");
      out.write("                        <th style=\"text-align: center; font:bold; font-size: 20px; \"></th>\n");
      out.write("                        <td>\n");
      out.write("\t\t                  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/fileUpload.jsp", out, false);
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                      </tr>\n");
      out.write("                  </table>\n");
      out.write("                  \n");
      out.write("                  <button type=\"submit\" id=\"subBtn\" class=\" mt-5 btn btn-block btn-outline-secondary\"\n");
      out.write("                    style=\"float: right; margin-right: 2%; width: 100px; height: 40px;\">글 등록</button>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.col-->\n");
      out.write("          </div>\n");
      out.write("          <!-- ./row -->\n");
      out.write("        </section>\n");
      out.write("      </form>\n");
      out.write("      </section>\n");
      out.write("       </div>\n");
      out.write("      <!-- /.content -->\n");
      out.write("    <!-- /.content-wrapper -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/sidebar.jsp", out, false);
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("  </div>\n");
      out.write("  <!-- ./wrapper -->\n");
      out.write("<!-- Control Sidebar -->\n");
      out.write("    <aside class=\"control-sidebar control-sidebar-dark\">\n");
      out.write("      <!-- Control sidebar content goes here -->\n");
      out.write("    </aside>\n");
      out.write("    <!-- /.control-sidebar -->\n");
      out.write("  <!-- jQuery -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("  <!-- Bootstrap 4 -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("  <!-- AdminLTE App -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/dist/js/adminlte.min.js\"></script>\n");
      out.write("  <!-- AdminLTE for demo purposes -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/dist/js/demo.js\"></script>\n");
      out.write("  <!-- Summernote -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/summernote/summernote-bs4.min.js\"></script>\n");
      out.write("  <!-- Select2 -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/select2/js/select2.full.min.js\"></script>\n");
      out.write("  <!-- Bootstrap4 Duallistbox -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js\"></script>\n");
      out.write("  <!-- InputMask -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/moment/moment.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/inputmask/min/jquery.inputmask.bundle.min.js\"></script>\n");
      out.write("  <!-- date-range-picker -->\n");
      out.write("\n");
      out.write("  <!-- bootstrap color picker -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js\"></script>\n");
      out.write("  <!-- Tempusdominus Bootstrap 4 -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js\"></script>\n");
      out.write("  <!-- Bootstrap Switch -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/bootstrap-switch/js/bootstrap-switch.min.js\"></script>\n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("    // $(function () {\n");
      out.write("    //   // Summernote\n");
      out.write("    //   $('.textarea').summernote({\n");
      out.write("    //     height: 500\n");
      out.write("    //   })\n");
      out.write("    // });\n");
      out.write("\n");
      out.write("    $(function () {\n");
      out.write("      //Initialize Select2 Elements\n");
      out.write("      $('.select2').select2()\n");
      out.write("\n");
      out.write("      //Initialize Select2 Elements\n");
      out.write("      $('.select2bs4').select2({\n");
      out.write("        theme: 'bootstrap4'\n");
      out.write("      })\n");
      out.write("\n");
      out.write("      //Datemask dd/mm/yyyy\n");
      out.write("      $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })\n");
      out.write("      //Datemask2 mm/dd/yyyy\n");
      out.write("      $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })\n");
      out.write("      //Money Euro\n");
      out.write("      $('[data-mask]').inputmask()\n");
      out.write("\n");
      out.write("      //Date range picker\n");
      out.write("      $('#reservation').daterangepicker()\n");
      out.write("\n");
      out.write("      //Bootstrap Duallistbox\n");
      out.write("      $('.duallistbox').bootstrapDualListbox()\n");
      out.write("\n");
      out.write("      //Colorpicker\n");
      out.write("      $('.my-colorpicker1').colorpicker()\n");
      out.write("      //color picker with addon\n");
      out.write("      $('.my-colorpicker2').colorpicker()\n");
      out.write("\n");
      out.write("      $('.my-colorpicker2').on('colorpickerChange', function (event) {\n");
      out.write("        $('.my-colorpicker2 .fa-square').css('color', event.color.toString());\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      $(\"input[data-bootstrap-switch]\").each(function () {\n");
      out.write("        $(this).bootstrapSwitch('state', $(this).prop('checked'));\n");
      out.write("      });\n");
      out.write("\n");
      out.write("    })\n");
      out.write("  </script>\n");
      out.write("\n");
      out.write("  <!-- bs-custom-file-input -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/bs-custom-file-input/bs-custom-file-input.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("    $(document).ready(function () {\n");
      out.write("      bsCustomFileInput.init();\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    $(\"#subBtn\").on(\"click\", function(e){\n");
      out.write("    \t/* 제목 입력 유효성 */\n");
      out.write("    \tif($(\"#inputTitle\").val() == ''){\n");
      out.write("    \t\talert('제목을 입력해주세요.');\n");
      out.write("    \t\t$(\"#inputTitle\").focus();\n");
      out.write("    \t\tvar checkColla = document.getElementsByName('depts');\n");
      out.write("    \t\treturn ;\n");
      out.write("    \t}\n");
      out.write("    \t\n");
      out.write("    \t/* 대상 부서 선택 유효성 */\n");
      out.write("    \t/* if(){\n");
      out.write("    \t\talert('협업 대상 부서를 1개 이상 선택해주세요.');\n");
      out.write("    \t\treturn false;\n");
      out.write("    \t}   */\n");
      out.write("    \t\n");
      out.write("    \t/* 업무기한 시작일 유효성 */\n");
      out.write("    \tif($('input#from').val() == ''){\n");
      out.write("    \t\talert('시작일을 선택해주세요.');\n");
      out.write("    \t\t$('input#from').focus();\n");
      out.write("    \t\treturn ;\n");
      out.write("    \t\t\n");
      out.write("    \t}else if($('input#to').val() == ''){\n");
      out.write("    \t\talert('종료일을 선택해주세요.');\n");
      out.write("    \t\t$('input#to').focus();\n");
      out.write("    \t\treturn ;\n");
      out.write("    \t} else if($('input#from').val() != '' && $('input#to').val() != '' ){\n");
      out.write("\t\t\tvar toArr = $('input#to').val().split('-');\n");
      out.write("\t   \t\tvar fromArr =  $('input#from').val().split('-');  \t\n");
      out.write("\t   \t\tvar toDt = new Date(toArr[0], Number(toArr[1])-1, toArr[2]);\n");
      out.write("\t   \t\tvar fromDt = new Date(fromArr[0], Number(fromArr[1])-1, fromArr[2]);\n");
      out.write("\t   \t\tvar betweenDt = // (toDt.getTime() - fromDt.getTime())/1000/60/60/24; \n");
      out.write("\t   \t\tMath.ceil((toDt.getTime()-fromDt.getTime())/(1000*3600*24));\n");
      out.write("\n");
      out.write("\t   \t/* \tfor(var i=0;i<toArr.length;i++){\n");
      out.write("\t   \t\t\tif(fromArr[i]>toArr[i]){\n");
      out.write("\t   \t\t\t\talert(\"종료일은 시작일 보다 작을 수 없습니다.\");\n");
      out.write("\t\t    \t\t$('input#to').focus();\n");
      out.write("\t   \t\t\t\treturn false;\n");
      out.write("\t   \t\t\t\t}\n");
      out.write("\t   \t\t\t} */\n");
      out.write("\t   \t\t\n");
      out.write("\t   \t\tconsole.log(betweenDt);\n");
      out.write("    \t\t$(\"#betweenDt\").text(betweenDt+\" 일간\");\n");
      out.write("\t   \t\t\n");
      out.write("   \t\t}\n");
      out.write("            \n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write("<!-- ./wrapper -->\n");
      out.write("\n");
      out.write("<!-- REQUIRED SCRIPTS -->\n");
      out.write("\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<!-- AdminLTE -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/dist/js/adminlte.js\"></script>\n");
      out.write("\n");
      out.write("<!-- OPTIONAL SCRIPTS -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/chart.js/Chart.min.js\"></script>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/dist/js/demo.js\"></script>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/dist/js/pages/dashboard3.js\"></script>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/plugins/daterangepicker/daterangepicker.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/collaboBoard/collaboBoardEditors.jsp(66,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("loginDeptCode");
      // /WEB-INF/views/collaboBoard/collaboBoardEditors.jsp(66,24) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/collaboBoard/collaboBoardEditors.jsp(66,24) '${loginMember.deptCode}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${loginMember.deptCode}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/collaboBoard/collaboBoardEditors.jsp(69,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dList");
      // /WEB-INF/views/collaboBoard/collaboBoardEditors.jsp(69,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/collaboBoard/collaboBoardEditors.jsp(69,24) '${deptList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${deptList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/collaboBoard/collaboBoardEditors.jsp(69,24) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("vs");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" \n");
            out.write("                        ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/collaboBoard/collaboBoardEditors.jsp(70,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.deptCode != dList.deptCode}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                          <div class=\"icheck-primary d-inline mr-5\" style=\"width:100%\">\n");
          out.write("                            <input type=\"checkbox\" name=\"collaboDept\" id=\"checkDept");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vs.index+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dList.deptName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\n");
          out.write("                            <label for=\"checkDept");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vs.index+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dList.deptName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</label>\n");
          out.write("                          </div>\n");
          out.write("                          ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
