/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-11 07:35:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang = \"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("   <meta name=\"viewport\"\r\n");
      out.write("      content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>(주)O.正 상사 인트라넷 로그인</title>\r\n");
      out.write("   <link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("      integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("      crossorigin=\"anonymous\">\r\n");
      out.write("   <style type=\"text/css\">\r\n");
      out.write("      /* body * {\r\n");
      out.write("         border: 1px solid red;\r\n");
      out.write("         box-sizing: border-box;\r\n");
      out.write("      } */\r\n");
      out.write("      body {\r\n");
      out.write("         \r\n");
      out.write("         background: linear-gradient(rgb(83,83,83), rgb(32,33,36)) fixed;\r\n");
      out.write("         color:rgb(195,195,195);\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .tp{\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-left: auto;\r\n");
      out.write("        margin-right: auto;\r\n");
      out.write("        margin-top: 10%;\r\n");
      out.write("        margin-bottom: auto;\r\n");
      out.write("        width: 30%;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .loginBtn{\r\n");
      out.write("         width : 100px;\r\n");
      out.write("         height : 95px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      img {\r\n");
      out.write("         width : 150px;\r\n");
      out.write("      }\r\n");
      out.write("   </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"tp\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("   <div class=\"row\">\r\n");
      out.write("      <div class=\"col-md-12\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\" style=\"\">\r\n");
      out.write("               <h1 class=\"text-left\"><b style=\"color:rgb(238,238,238); width:160px; display:inline-block\">오정상사</b> <b style=\"color:rgb(183,198,235); display:inline-block\">로그인</b></h1>\r\n");
      out.write("               <p style=\" width:380px; display:inline-block\"><br>오정 그룹 내부에서 사용하는 페이지 입니다.<br>외부인들의 접근을 금합니다.</p>\r\n");
      out.write("      \r\n");
      out.write("               <img src=\"resources/images/lock.png\" style=\" display:inline-block\"/>\r\n");
      out.write("               <!-- <img alt=\"Bootstrap Image Preview\" src=\"https://www.layoutit.com/img/sports-q-c-140-140-3.jpg\" /> -->\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("               <h3>\r\n");
      out.write("                  <h3>LOGIN</h3>\r\n");
      out.write("                  <p style=\" width:500px; \">사내 이메일과 비밀번호를 입력하신 후 로그인 버튼을 눌러주세요.</p>\r\n");
      out.write("               </h3>\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-md-12\">\r\n");
      out.write("                  <form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/login\" method=\"post\">\r\n");
      out.write("                  <table class=\"\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                     <td class=\"input-group-prepend mt-3\" style=\"width:80px; display:inline-block\">&nbsp;&nbsp;이메일 </td>\r\n");
      out.write("                     <td style=\"width:400px;\">\r\n");
      out.write("                        <input class=\"input-group-text\" type=\"text\" size=\"40\" maxlength=\"50\"\r\n");
      out.write("                        placeholder=\"이메일을 입력해주세요.\" name=\"memberEmail\" required>\r\n");
      out.write("                     <td colspan=\"2\" rowspan=\"2\">\r\n");
      out.write("                         <button class=\"loginBtn m-2 btn btn-success \" type=\"submit\">Login</button>\r\n");
      out.write("                     </td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                     <td>비밀번호 </td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input class=\"input-group-text\" type=\"password\" size=\"40\" maxlength=\"50\"\r\n");
      out.write("                         placeholder=\"비밀번호를 입력해주세요.\" name=\"memberPwd\" required>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("         <div class=\"alert alert-success alert-dismissable\" hidden>\r\n");
      out.write("             \r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">\r\n");
      out.write("               ×\r\n");
      out.write("            </button>\r\n");
      out.write("            <h4>\r\n");
      out.write("               Alert!\r\n");
      out.write("            </h4> <strong>Warning!</strong> Best check yo self, you're not looking too good. <a href=\"#\" class=\"alert-link\">alert link</a>\r\n");
      out.write("         </div> \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("      integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("      integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("      integrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
